### Get the secret ingredient.
GET https://localhost:5091/secret/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hcmtqIiwic3ViIjoibWFya2oiLCJqdGkiOiJmMmQxNGRmYSIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjUwOTAiLCJodHRwczovL2xvY2FsaG9zdDo1MDkxIl0sIm5iZiI6MTcyNDUwMzE5NCwiZXhwIjoxNzMyNDUxOTk0LCJpYXQiOjE3MjQ1MDMxOTUsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.grLo3oRI2j2-LuF7IEZSLxjVFOh57FcRWO9SyC4se2M
